# Stage 1: Build
FROM node:20-alpine3.19 AS builder

WORKDIR /app

COPY package.json ./

RUN npm i

COPY . .

RUN npm run build:dev


# Stage 2: Production
FROM node:20-alpine3.19

WORKDIR /app

COPY --from=builder /app/dist /app/dist

RUN npm install -g serve

EXPOSE 3000

CMD ["serve", "dist"]